[build]
  base = "portfolio-app"
  command = "npm run build"
  publish = "portfolio-app/build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
