[build]
  base = "portfolio-app"
  command = "CI=false npm run build"
  publish = "portfolio-app/build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
